<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <None Include="..\..\icon.png" Pack="true" PackagePath="" />
        <None Include="..\..\README.md" Pack="true" PackagePath="" />
    </ItemGroup>

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Haitch.Unions\Haitch.Unions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="TUnit.Assertions" />
    </ItemGroup>

    <PropertyGroup>
        <PackageId>Haitch.Unions.TUnit.Assertions</PackageId>
        <Description>TUnit assertions for Haitch.Unions.</Description>
        <PackageTags>result;optional;union;errors;functional;railway;haitch;foundational;unit-tests;tunit</PackageTags>
        <PackageIcon>icon.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
</Project>
