<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Haitch.Unions.TUnit.Assertions\Haitch.Unions.TUnit.Assertions.csproj" />
        <ProjectReference Include="..\..\src\Haitch.Unions\Haitch.Unions.csproj" />
    </ItemGroup>
</Project>
