<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

    <PropertyGroup>
        <Authors>Hayden Quinn</Authors>
        <Company>Haitch</Company>
        <Copyright>Copyright © Hayden Quinn $([System.DateTime]::Now.Year)</Copyright>
        <PackageProjectUrl>https://haitch.dev</PackageProjectUrl>
        <RepositoryUrl>https://github.com/HaitchDev/Haitch.Unions</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageIcon>icon.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
        <Deterministic>true</Deterministic>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Version Condition="'$(Version)' == ''">0.0.0-dev</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
